export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const PASSWORD_SCREEN = 'PASSWORD_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const INITIALIZING_SCREEN = 'INITIALIZING_SCREEN';
export const PROFILE_STACK = 'PROFILE_STACK';

//For Main Navigators
export const LOGIN_ROOT = 'LOGIN_ROOT';
export const APP_ROOT = 'APP_ROOT_SCREEN';
export const APP_ROOT_TABS = 'APP_ROOT_TABS';
export const CHANGE_PASSWORD_SCREEN = 'CHANGE_PASSWORD_SCREEN';